AWSTemplateFormatVersion: "2010-09-09"
Description: Create VPN Server

Parameters:
  EC2KeyPairName:
    Type: String
    Description: EC2 Key Pair Name you have

  VPNUntrustSubnetId:
    Type: String
    Description: Subnet ID for VPN Untrust Subnet

  VPNTrustSubnetId:
    Type: String
    Description: Subnet ID for VPN Subnet

  VPNUntrustSecurityGroupId:
    Type: String
    Description: VPN Untrust Nettwork Security Group ID for VPN Server

  VPNTrustSecurityGroupId:
    Type: String
    Description: VPN Trust Network Security Group ID for VPN Server

  VPNUntrustIp:
    Type: String
    Description: VPN Server IP address on VPN Untrust Network

  VPNTrustIp:
    Type: String
    Description: VPN Server IP address on VPN Trust Network

  PrivateRouteTableId:
    Type: String
    Description: Private Route Table ID

  PublicRouteTableId:
    Type: String
    Description: Public Route Table ID

  VPNTunnelCidr:
    Type: String
    Description: Virutal Network's Cidr

Resources:
  VPNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: VPN
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                Resource:
                  - "*"

  VPNRoleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref VPNRole

  VPNLambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "VPNLambdaExecPolicy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeImages"
                  - "ec2:ModifyNetworkInterfaceAttribute"
                  - "logs:*"
                Resource:
                  - "*"

  SpotFleetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "spotfleet.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole

  GetAMIIDLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import json
          import cfnresponse
          import traceback
          def handler(event, context):
            responseData = {}
            try:
              target = "vpn"
              ec2 = boto3.client("ec2")
              if event["RequestType"] == "Delete":
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                return
              ec2Info = ec2.describe_images(Filters = [{"Name": "tag:Name", "Values": [target]}])
              responseData["Id"] = ec2Info["Images"][0]["ImageId"]
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, "Id")
              return
            except:
              traceback_exc()
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
              return
      Runtime: python2.7
      Timeout: 900
      Handler: index.handler
      MemorySize: 128
      FunctionName: GetAMIID
      Role: !GetAtt VPNLambdaExecRole.Arn
      Tags:
        - Key: Environment
          Value: vpn
        - Key: Name
          Value: GetAMIId

  GetAMIID:
    Type: Custom::GetAMIID
    Properties:
      ServiceToken: !GetAtt GetAMIIDLambda.Arn

  VPNServer:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt SpotFleetRole.Arn
        TerminateInstancesWithExpiration: false
        InstanceInterruptionBehavior: stop
        TargetCapacity: 1
        LaunchSpecifications:
          - EbsOptimized: true
            IamInstanceProfile:
              Arn: !GetAtt VPNRoleProfile.Arn
            ImageId: !GetAtt GetAMIID.Id
            InstanceType: t3.small
            KeyName: !Ref EC2KeyPairName
            Monitoring:
              Enabled: false
            NetworkInterfaces:
              - AssociatePublicIpAddress: true
                DeleteOnTermination: true
                Description: VPN untrust ENI
                DeviceIndex: 0
                PrivateIpAddresses:
                  - Primary: true
                    PrivateIpAddress: !Ref VPNUntrustIp
                Groups:
                  - !Ref VPNUntrustSecurityGroupId
                  - !ImportValue DevelopmentSecurityGroupId
                SubnetId: !Ref VPNUntrustSubnetId
            SpotPrice: 1
            TagSpecifications:
              - ResourceType: instance
                Tags:
                  - Key: Environment
                    Value: vpn
                  - Key: Name
                    Value: vpn
  
  TrustNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: VPN trust ENI
      GroupSet:
        - !Ref VPNTrustSecurityGroupId
      PrivateIpAddress: !Ref VPNTrustIp
      SubnetId: !Ref VPNTrustSubnetId
      Tags:
        - Key: Environment
          Value: vpn
        - Key: Name
          Value: trust

Outputs:
  VPNLambdaExecRoleArn:
    Value: !GetAtt VPNLambdaExecRole.Arn

  TrustNetworkInterfaceId:
    Value: !Ref TrustNetworkInterface
