AWSTemplateFormatVersion: "2010-09-09"
Description: Create VPN Server

Parameters:
  EC2KeyPairName:
    Type: String
    Description: EC2 Key Pair Name you have

  VPNSubnetId:
    Type: String
    Description: Subnet ID for VPN Subnet

  VPNSecurityGroupId:
    Type: String
    Description: Security Group ID for VPN Server

  VPNServerIp:
    Type: String
    Description: VPN Server IP address

  PrivateRouteTableId:
    Type: String
    Description: Private Route Table ID

  VPNTunnelCidr:
    Type: String
    Description: Virutal Network's Cidr

Resources:
  VPNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: VPN
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                Resource:
                  - "*"

  VPNRoleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref VPNRole

  VPNLambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "VPNLambdaExecPolicy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:*"
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeImages"
                  - "ec2:ModifyNetworkInterfaceAttribute"
                  - "logs:*"
                Resource:
                  - "*"

  SpotFleetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "spotfleet.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole

  GetAMIIDLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import json
          import cfnresponse
          def deleteLogs(target):
            logs = boto3.client("logs")
            logGroups = logs.describe_log_groups()
            for logGroup in logGroups["logGroups"]:
              if target in logGroup["logGroupName"]:
                logs.delete_log_group(logGroupName=logGroup["logGroupName"])
            return
          def handler(event, context):
            responseData = {}
            deleteLogs("GetAMIIDLambda")
            try:
              target = "vpn"
              ec2 = boto3.client("ec2")
              if event["RequestType"] == "Delete":
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                return
              ec2Info = ec2.describe_images(Filters = [{"Name": "tag:Name", "Values": [target]}])
              responseData["Id"] = ec2Info["Images"][0]["ImageId"]
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, "Id")
              return
            except Exception:
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
              return
      Runtime: python2.7
      Timeout: 30
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt VPNLambdaExecRole.Arn

  GetAMIID:
    Type: Custom::GetAMIID
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt GetAMIIDLambda.Arn

  VPNServer:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt SpotFleetRole.Arn
        TerminateInstancesWithExpiration: false
        InstanceInterruptionBehavior: stop
        TargetCapacity: 1
        LaunchSpecifications:
          - EbsOptimized: true
            IamInstanceProfile:
              Arn: !GetAtt VPNRoleProfile.Arn
            ImageId: !GetAtt GetAMIID.Id
            InstanceType: t3.small
            KeyName: !Ref EC2KeyPairName
            Monitoring:
              Enabled: false
            NetworkInterfaces:
              - AssociatePublicIpAddress: true
                DeleteOnTermination: true
                DeviceIndex: 0
                PrivateIpAddresses:
                  - Primary: true
                    PrivateIpAddress: !Ref VPNServerIp
                Groups:
                  - !Ref VPNSecurityGroupId
                SubnetId: !Ref VPNSubnetId
            SpotPrice: 1
            TagSpecifications:
              - ResourceType: instance
                Tags:
                  - Key: Environment
                    Value: vpn
                  - Key: Name
                    Value: vpn

Outputs:
  VPNLambdaExecRoleArn:
    Value: !GetAtt VPNLambdaExecRole.Arn

  VPNAMIID:
    Value: !GetAtt GetAMIID.Id
