AWSTemplateFormatVersion: 2010-09-09
Description: Manage Nested Stacks

Parameters:
  StackS3URL:
    Type: String
    Default: https://s3.ap-northeast-1.amazonaws.com/00-cfn-repository

  VPCCidr:
    Type: String
    Default: 10.3.0.0/16

  VPNTunnelCidr:
    Type: String
    Default: 10.8.0.0/24

  VPNUntrustIp:
    Type: String
    Default: 10.3.255.250

  VPNTrustIp:
    Type: String
    Default: 10.3.255.230

  NTPServerIp:
    Type: String
    Default: 169.254.169.254

  DomainName:
    Type: String
    Default: tuimac.private

  VPNUntrustSubnetCidr:
    Type: String
    Default: 10.3.255.240/28

  VPNTrustSubnetCidr:
    Type: String
    Default: 10.3.255.224/28

  PrivateSubnetCidr:
    Type: String
    Default: 10.3.0.0/26

  PublicSubnetCidr:
    Type: String
    Default: 10.3.0.64/26

  EndpointSubnetCidr:
    Type: String
    Default: 10.3.0.128/26

  EC2KeyPairName:
    Type: String
    Default: tuimac

Resources:
  VPNNetwork:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - ${URL}/network/network.yml
        - URL: !Ref StackS3URL
      Parameters:
        VPCCidr: !Ref VPCCidr
        VPNTrustIp: !Ref VPNTrustIp
        NTPServerIp: !Ref NTPServerIp
        DomainName: !Ref DomainName
        VPNUntrustSubnetCidr: !Ref VPNUntrustSubnetCidr
        VPNTrustSubnetCidr: !Ref VPNTrustSubnetCidr
        PrivateSubnetCidr: !Ref PrivateSubnetCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr
        EndpointSubnetCidr: !Ref EndpointSubnetCidr

  VPNSecurities:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: VPNNetwork
    Properties:
      TemplateURL: !Sub
        - ${URL}/network/security.yml
        - URL: !Ref StackS3URL
      Parameters:
        VPCId: !GetAtt VPNNetwork.Outputs.VPCId
        VPCCidr: !Ref VPCCidr
        PrivateSubnetCidr: !Ref PrivateSubnetCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr
        VPNTunnelCidr: !Ref VPNTunnelCidr

  VPNServer:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: VPNSecurities
    Properties:
      TemplateURL: !Sub
        - ${URL}/vpn/vpn.yml
        - URL: !Ref StackS3URL
      Parameters:
        EC2KeyPairName: !Ref EC2KeyPairName
        VPNUntrustSubnetId: !GetAtt VPNNetwork.Outputs.VPNUntrustSubnetId
        VPNTrustSubnetId: !GetAtt VPNNetwork.Outputs.VPNTrustSubnetId
        VPNUntrustSecurityGroupId: !GetAtt VPNSecurities.Outputs.VPNUntrustSecurityGroupId
        VPNTrustSecurityGroupId: !GetAtt VPNSecurities.Outputs.VPNTrustSecurityGroupId
        VPNUntrustIp: !Ref VPNUntrustIp
        VPNTrustIp: !Ref VPNTrustIp
        PrivateRouteTableId: !GetAtt VPNNetwork.Outputs.PrivateRouteTableId
        PublicRouteTableId: !GetAtt VPNNetwork.Outputs.PublicRouteTableId
        VPNTunnelCidr: !Ref VPNTunnelCidr

  GetPublicIpAndBackup:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: VPNServer
    Properties:
      TemplateURL: !Sub
        - ${URL}/vpn/getpublicipAndbackup.yml
        - URL: !Ref StackS3URL

Outputs:
  EC2KeyPairName:
    Value: !Ref EC2KeyPairName
    Export:
      Name: EC2KeyPairName

  VPNServerPublicIp:
    Value: !GetAtt GetPublicIpAndBackup.Outputs.VPNServerPublicIp
    Export:
      Name: VPNServerPublicIp
