AWSTemplateFormatVersion: 2010-09-09
Description: Manage Core Infrastructure Stack

Parameters:
  BaseTemplateURL:
    Description: This template's root directory name on S3 bucket.
    Type: String
    Default: https://00-cfn-repository.s3.ap-northeast-1.amazonaws.com/baseInfrastructure

  VPNVpcCidr:
    Type: String
    Default: 10.3.0.0/16

  VPNUntrustSubnetCidr:
    Type: String
    Default: 10.3.255.240/28

  VPNTrustSubnetCidr:
    Type: String
    Default: 10.3.255.224/28

  VPNPrivateSubnetACidr:
    Type: String
    Default: 10.3.0.0/26

  VPNPrivateSubnetCCidr:
    Type: String
    Default: 10.3.0.64/26

  VPNPrivateSubnetDCidr:
    Type: String
    Default: 10.3.0.128/26

  VPNPublicSubnetACidr:
    Type: String
    Default: 10.3.0.192/26

  VPNPublicSubnetCCidr:
    Type: String
    Default: 10.3.1.0/26

  VPNPublicSubnetDCidr:
    Type: String
    Default: 10.3.1.64/26

  VPNEndpointSubnetACidr:
    Type: String
    Default: 10.3.1.128/26

  VPNEndpointSubnetCCidr:
    Type: String
    Default: 10.3.1.192/26
 
  VPNEndpointSubnetDCidr:
    Type: String
    Default: 10.3.2.0/26

  VPNTunnelCidr:
    Type: String
    Default: 10.2.0.0/29

  VPNNTPServerIp:
    Type: String
    Default: 169.254.169.254

  VPNDomainName:
    Type: String
    Default: tuimac.private

  VPNDNSPrimary:
    Description: Recommend to set VPN Trust ip address.
    Type: String
    Default: 10.3.255.230

  VPNDNSSecondary:
    Type: String
    Default: 8.8.8.8

  VPNTagKey:
    Description: Export this value.
    Type: String
    Default: Environment

  VPNTagValue:
    Description: Export this value.
    Type: String
    Default: vpn

Resources:
  VPNNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - ${URL}/network.yaml
        - URL: !Ref BaseTemplateURL
      Parameters:
        VPNVpcCidr: !Ref VPNVpcCidr
        VPNUntrustSubnetCidr: !Ref VPNUntrustSubnetCidr
        VPNTrustSubnetCidr: !Ref VPNTrustSubnetCidr
        VPNPrivateSubnetACidr: !Ref VPNPrivateSubnetACidr
        VPNPrivateSubnetCCidr: !Ref VPNPrivateSubnetCCidr
        VPNPrivateSubnetDCidr: !Ref VPNPrivateSubnetDCidr
        VPNPublicSubnetACidr: !Ref VPNPublicSubnetACidr
        VPNPublicSubnetCCidr: !Ref VPNPublicSubnetCCidr
        VPNPublicSubnetDCidr: !Ref VPNPublicSubnetDCidr
        VPNEndpointSubnetACidr: !Ref VPNEndpointSubnetACidr
        VPNEndpointSubnetCCidr: !Ref VPNEndpointSubnetCCidr
        VPNEndpointSubnetDCidr: !Ref VPNEndpointSubnetDCidr
        VPNNTPServerIp: !Ref VPNNTPServerIp
        VPNDomainName: !Ref VPNDomainName
        VPNDNSPrimary: !Ref VPNDNSPrimary
        VPNDNSSecondary: !Ref VPNDNSSecondary
        VPNTagKey: !Ref VPNTagKey
        VPNTagValue: !Ref VPNTagValue

  VPNSecurityGroup:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPNNetwork
    Properties:
      TemplateURL: !Sub
        - ${URL}/securitygroup.yaml
        - URL: !Ref BaseTemplateURL
      Parameters:
        VPNVpcCidr: !Ref VPNVpcCidr
        VPNTunnelCidr: !Ref VPNTunnelCidr
        VPNTagKey: !Ref VPNTagKey
        VPNTagValue: !Ref VPNTagValue

  VPNLambdaExecutionRole:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPNSecurityGroup
    Properties:
      TemplateURL: !Sub
        - ${URL}/lambdaExecutionRole.yaml
        - URL: !Ref BaseTemplateURL
      Parameters:
        VPNTagKey: !Ref VPNTagKey
        VPNTagValue: !Ref VPNTagValue

Outputs:
  VPNTunnelCidr:
    Value: !Ref VPNTunnelCidr
    Export:
      Name: VPNTunnelCidr

  VPNTagKey:
    Value: !Ref VPNTagKey
    Export:
      Name: VPNTagKey

  VPNTagValue:
    Value: !Ref VPNTagValue
    Export:
      Name: VPNTagValue
