AWSTemplateFormatVersion: 2010-09-09
Description: Manage Nested Stacks
Resources:
  VPNNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/00-cloudformation/41a974a9524f4e68395f793432a84a9b.template
  VPNSecurities:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/00-cloudformation/b7521c896eb3df0660c098dc02a5e03f.template
      Parameters:
        VPCId:
          Fn::GetAtt:
          - VPNNetwork
          - Outputs.VPCId
        PrivateSubnetCidr:
          Fn::GetAtt:
          - VPNNetwork
          - Outputs.PrivateSubnetCidr
  VPNServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/00-cloudformation/c2d914d6c0b777af1ca20fd06dde0215.template
      Parameters:
        VPNSubnetId:
          Fn::GetAtt:
          - VPNNetwork
          - Outputs.VPNSubnetId
        VPNSecurityGroupId:
          Fn::GetAtt:
          - VPNSecurities
          - Outputs.VPNSecurityGroupId
        VPNServerIp:
          Fn::GetAtt:
          - VPNNetwork
          - Outputs.VPNServerIp
        PrivateRouteTableId:
          Fn::GetAtt:
          - VPNNetwork
          - Outputs.PrivateRouteTableId
        VPNTunnelCidr:
          Fn::GetAtt:
          - VPNSecurities
          - Outputs.VPNTunnelCidr
  AddRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/00-cloudformation/bb40ee045e94d7d9f4942706459ec892.template
      Parameters:
        PrivateRouteTableId:
          Fn::GetAtt:
          - VPNNetwork
          - Outputs.PrivateRouteTableId
        VPNTunnelCidr:
          Fn::GetAtt:
          - VPNSecurities
          - Outputs.VPNTunnelCidr
        VPNLambdaExecRoleArn:
          Fn::GetAtt:
          - VPNServer
          - Outputs.VPNLambdaExecRoleArn
