AWSTemplateFormatVersion: "2010-09-09"
Description: Create environment for session manager

Resources:
  EC2Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !ImportValue EndpointSecurityGroupId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2
      SubnetIds: 
        - !ImportValue EndpointSubnetId
      VpcEndpointType: Interface
      VpcId: !ImportValue VPCId
