AWSTemplateFormatVersion: 2010-09-09
Description: Security

Parameters:
  VPCId:
    Type: String
    Description: VPC ID

  VPCCidr:
    Type: String
    Description: Cidr for Entire Network

  PrivateSubnetCidr:
    Type: String
    Description: Cidr for Private Subnet

  PublicSubnetCidr:
    Type: String
    Description: Cidr for Public Subnet

  VPNTunnelCidr:
    Type: String
    Description: Internet VPN Cidr

Resources:
  VPNUntrustSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: VpnUntrust
      GroupDescription: for VPN Untrust Network
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
      SecurityGroupEgress:
        - IpProtocol: udp
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
        - IpProtocol: -1
          CidrIp: !Ref VPCCidr
          Description: VPC Network
      Tags:
        - Key: Environment
          Value: vpn
        - Key: Name
          Value: vpn-untrust

  VPNTrustSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: VpnTrust
      GroupDescription: for VPN Trust Network
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
      SecurityGroupEgress:
        - IpProtocol: udp
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
        - IpProtocol: -1
          CidrIp: !Ref VPCCidr
          Description: VPC Network
      Tags:
        - Key: Environment
          Value: vpn
        - Key: Name
          Value: vpn-trust

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: VpnPrivate
      GroupDescription: for Private
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref PrivateSubnetCidr
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: !Ref PrivateSubnetCidr
          Description: VPC Network
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
        - IpProtocol: tcp
          FromPort: 433
          ToPort: 433
          DestinationPrefixListId: pl-61a54008
          Description: To S3 bucket through Endpoint
      Tags:
        - Key: Environment
          Value: vpn
        - Key: Name
          Value: private

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: VpnPublic
      GroupDescription: for Public
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref PublicSubnetCidr
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
        - IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1
          Description: Echo request from ANY
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: !Ref PublicSubnetCidr
          Description: VPC Network
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
        - IpProtocol: tcp
          FromPort: 433
          ToPort: 433
          DestinationPrefixListId: pl-61a54008
          Description: To S3 bucket through Endpoint
        - IpProtocol: tcp
          FromPort: 433
          ToPort: 433
          CidrIp: 0.0.0.0/0
          Description: Allow access to the Internet by HTTPS
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow access to the Internet by HTTP
        - IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1
          Description: Echo request to ANY
      Tags:
        - Key: Environment
          Value: vpn
        - Key: Name
          Value: public

  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: VpnEndpoint
      GroupDescription: for Endpoint
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref PrivateSecurityGroup
          Description: From EC2 with Private SecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          DestinationSecurityGroupId: !Ref PrivateSecurityGroup
          Description: To EC2 with Private SecurityGroup
      Tags:
        - Key: Environment
          Value: vpn
        - Key: Name
          Value: endpoint

Outputs:
  VPNUntrustSecurityGroupId:
    Value: !Ref VPNUntrustSecurityGroup

  VPNTrustSecurityGroupId:
    Value: !Ref VPNTrustSecurityGroup

  PrivateSecurityGroupId:
    Value: !Ref PrivateSecurityGroup
    Export:
      Name: PrivateSecurityGroupId

  PublicSecurityGroupId:
    Value: !Ref PublicSecurityGroup
    Export:
      Name: PublicSecurityGroupId

  EndpointSecurityGroupId:
    Value: !Ref PrivateSecurityGroup
    Export:
      Name: EndpointSecurityGroupId
