AWSTemplateFormatVersion: 2010-09-09
Description: Add route to Private and Public RouteTables

Parameters:
  VPNTrustNetworkInterfaceId:
    Type: String

Resources:
  GetVPNInstanceIdLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import json
          import cfnresponse
          import time
          import traceback
          # Change all network interfaces SourceDestCheck setting
          def changeSourceDestCheck(ec2, instanceId):
            try:
              for i in range(80):
                ec2Info = ec2.describe_instances(
                  InstanceIds=[instanceId]
                )["Reservations"][0]["Instances"][0]
                if ec2Info["State"]["Name"] == "running":
                  for eni in ec2Info["NetworkInterfaces"]:
                    ec2.modify_network_interface_attribute(
                      NetworkInterfaceId=eni["NetworkInterfaceId"],
                      SourceDestCheck={"Value": False}
                    )
                  break
                time.sleep(1)
              return
            except Exception as e:
              raise e
          def handler(event, context):
            responseData = {}
            try:
              if event["RequestType"] == "Delete":
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                return
              # Specified instance with 'vpn' tag, get Netwowrk Interface ID and
              # change Source Dest Check
              target = event["ResourceProperties"]["TagValue"]
              ec2 = boto3.client("ec2")
              ec2Info = ec2.describe_instances(Filters=[{"Name": "tag:Name", "Values": [target]}])
              if len(ec2Info["Reservations"]) != 0:
                state = ""
                for instance in ec2Info["Reservations"]:
                  state = instance["Instances"][0]["State"]["Name"]
                  if state != "terminated":
                    changeSourceDestCheck(ec2, instance["Instances"][0]["InstanceId"])
                    responseData["Id"] = instance["Instances"][0]["InstanceId"]
                    responseData["ProgramLogicStatus"] = "Success to get instance ID"
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                    return
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                return
              else:
                responseData["ProgramLogicStatus"] = len(ec2Info["Reservations"])
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                return
            except:
              responseData["ProgramLogicStatus"] = traceback.format_exc()
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
              return
      Runtime: python2.7
      Timeout: 90
      Handler: index.handler
      MemorySize: 128
      FunctionName: GetVPNInstanceId
      Role: !ImportValue VPNLambdaExecutionRoleArn
      Tags:
        - Key: !ImportValue VPNTagKey
          Value: !ImportValue VPNTagValue
        - Key: Name
          Value: GetVPNInstanceId

  GetVPNInstanceId:
    Type: Custom::GetVPNInstanceId
    Properties:
      ServiceToken: !GetAtt GetVPNInstanceIdLambda.Arn
      TagValue: !ImportValue VPNTagKey

  AttachNetworkInterfaceToVPNInstance:
    Type: AWS::EC2::NetworkInterfaceAttachment
    Properties:
      DeviceIndex: 1
      DeleteOnTermination: true
      InstanceId: !GetAtt GetVPNInstanceId.Id
      NetworkInterfaceId: !Ref VPNTrustNetworkInterfaceId

  AddVPNRouteToPrivateRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue VPNPrivateRouteTableId
      NetworkInterfaceId: !Ref VPNTrustNetworkInterfaceId
      DestinationCidrBlock: !ImportValue VPNTunnelCidr

  AddRouteToPublicRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue VPNPublicRouteTableId
      NetworkInterfaceId: !Ref VPNTrustNetworkInterfaceId
      DestinationCidrBlock: !ImportValue VPNTunnelCidr
