AWSTemplateFormatVersion: 2010-09-09
Description: Get VPN instance's public ip

Resources:
  GetPublicIpLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import json
          import cfnresponse
          import time
          from datetime import date
          import traceback
          def handler(event, context):
            responseData = {}
            try:
              target = event["ResourceProperties"]["TagValue"]
              ec2 = boto3.client("ec2")
              if event["RequestType"] == "Delete":
                 cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                 return
              else:
                instances = ec2.describe_instances(
                  Filters=[{"Name": "tag:Name", "Values": [target]}]
                )["Reservations"]
                for instance in instances:
                  state = instance["Instances"][0]["State"]["Name"]
                  if state == "running":
                    responseData["Ip"] = instance["Instances"][0]["PublicIpAddress"]
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                    return
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                return
            except:
              traceback.print_exc()
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
              return
      Runtime: python2.7
      Timeout: 900
      Handler: index.handler
      MemorySize: 128
      Role: !ImportValue VPNLambdaExecutionRoleArn
      FunctionName: GetPublicIp
      Tags:
        - Key: !ImportValue VPNTagKey
          Value: !ImportValue VPNTagValue
        - Key: Name
          Value: VPN-Lambda-GetPublicIp

  GetPublicIp:
    Type: Custom::GetPublicIp
    Properties:
      ServiceToken: !GetAtt GetPublicIpLambda.Arn
      TagValue: !ImportValue VPNTagValue

Outputs:
  VPNInstancePublicIp:
    Value: !GetAtt GetPublicIp.Ip
    Export:
      Name: VPNInstancePublicIp
