AWSTemplateFormatVersion: 2010-09-09
Description: Manage Nested Stacks

Parameters:
  BaseTemplateURL:
    Description: Only S3 bucket URL to upload template.
    Type: String
    Default: https://00-cfn-repository.s3.ap-northeast-1.amazonaws.com

  VPNUntrustIp:
    Type: String
    Default: 10.3.255.250

  VPNTrustIp:
    Type: String
    Default: 10.3.255.230

  VPNInstanceType:
    Type: String
    Default: t3.small

Resources:
  CreateVPNInstance:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - ${URL}/vpnServer/createVpnInstance.yaml
        - URL: !Ref BaseTemplateURL
      Parameters:
        VPNUntrustIp: !Ref VPNUntrustIp
        VPNTrustIp: !Ref VPNTrustIp
        VPNInstanceType: !Ref VPNInstanceType

  AddVPNRoute:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: CreateVPNInstance
    Properties:
      TemplateURL: !Sub
        - ${URL}/vpnServer/addVpnRoute.yaml
        - URL: !Ref BaseTemplateURL
      Parameters:
        VPNTrustNetworkInterfaceId: !GetAtt CreateVPNInstance.Outputs.VPNTrustNetworkInterfaceId

  GetPublicIp:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: AddVPNRoute
    Properties:
      TemplateURL: !Sub
        - ${URL}/vpnServer/getPublicIp.yaml
        - URL: !Ref BaseTemplateURL

  BackupVPNInstance:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: GetPublicIp
    Properties:
      TemplateURL: !Sub
        - ${URL}/vpnServer/backupInstance.yaml
        - URL: !Ref BaseTemplateURL
