AWSTemplateFormatVersion: 2010-09-09
Description: Manage Nested Stacks

Resources:
  VPNNetwork:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./network/network.yml

  VPNSecurities:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./network/security.yml
      Parameters:
        VPCId: !GetAtt VPNNetwork.Outputs.VPCId
        PrivateSubnetCidr: !GetAtt VPNNetwork.Outputs.PrivateSubnetCidr

  VPNServer:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./vpn/vpn.yml
      Parameters:
        VPNSubnetId: !GetAtt VPNNetwork.Outputs.VPNSubnetId
        VPNSecurityGroupId: !GetAtt VPNSecurities.Outputs.VPNSecurityGroupId
        VPNServerIp: !GetAtt VPNNetwork.Outputs.VPNServerIp
        PrivateRouteTableId: !GetAtt VPNNetwork.Outputs.PrivateRouteTableId
        VPNTunnelCidr: !GetAtt VPNSecurities.Outputs.VPNTunnelCidr
