AWSTemplateFormatVersion: 2010-09-09
Description: Security

Parameters:
  VPCId:
    Type: String
    Description: VPC ID

  PrivateSubnetCidr:
    Type: String
    Description: Cidr for Private Subnet

  VPNTunnelCidr:
    Type: String
    Description: Internet VPN Cidr

Resources:
  VPNSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: for VPN
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
      SecurityGroupEgress:
        - IpProtocol: udp
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
        - IpProtocol: -1
          CidrIp: !Ref PrivateSubnetCidr
          Description: VPC Network
      Tags:
        - Key: Name
          Value: vpn

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: for Private
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref PrivateSubnetCidr
          Description: Internet VPN Port
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: !Ref PrivateSubnetCidr
          Description: VPC Network
        - IpProtocol: -1
          CidrIp: !Ref VPNTunnelCidr
          Description: VPN tunnel Network
        - IpProtocol: tcp
          FromPort: 433
          ToPort: 433
          DestinationPrefixListId: pl-61a54008
          Description: To S3 bucket through Endpoint
      Tags:
        - Key: Name
          Value: private

  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: for Endpoint
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref PrivateSecurityGroup
          Description: From EC2 with Private SecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          DestinationSecurityGroupId: !Ref PrivateSecurityGroup
          Description: To EC2 with Private SecurityGroup
      Tags:
        - Key: Name
          Value: endpoint

Outputs:
  VPNSecurityGroupId:
    Value: !Ref VPNSecurityGroup

  PrivateSecurityGroupId:
    Value: !Ref PrivateSecurityGroup
    Export:
      Name: PrivateSecurityGroupId

  EndpointSecurityGroupId:
    Value: !Ref PrivateSecurityGroup
    Export:
      Name: EndpointSecurityGroupId

  VPNTunnelCidr:
    Value: !Ref VPNTunnelCidr
